import type { AgencyContact } from "../../types/contracts";

const UPDATED_AT = "2026-05-10T00:00:00+08:00";

function blurb(en: string) {
  return { en, "zh-Hans": en };
}

export const agencies: AgencyContact[] = [
  {
    key: "hdb_essential_maintenance",
    name: "HDB Essential Maintenance Service Unit",
    hotline: "1800-225-5432",
    category: "hazard_authority",
    openingHours: "24 hours for essential maintenance",
    multilingualBlurb: blurb("For urgent HDB estate maintenance issues such as lift faults and water leaks."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "hdb_branch_office",
    name: "HDB Branch Office (general enquiries)",
    hotline: "1800-225-5432",
    category: "housing",
    openingHours: "Mon-Fri 8am-5pm",
    multilingualBlurb: blurb("General HDB matters: rental, upgrading, mailbox, and common-area issues."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "lta_customer_service",
    name: "Land Transport Authority Customer Service",
    hotline: "1800-225-5582",
    category: "hazard_authority",
    openingHours: "Mon-Fri 8.30am-6.30pm, Sat 8.30am-1pm",
    multilingualBlurb: blurb("Bus, MRT, taxi, concession-card, road, pavement, and transport infrastructure matters."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "transport_aid_silver_generation",
    name: "Silver Generation Transport Aid",
    category: "transport",
    multilingualBlurb: blurb("Subsidised transport help for medical appointments through SGO and partner agencies."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "aic_eldercare_hotline",
    name: "Agency for Integrated Care Hotline",
    hotline: "1800-650-6060",
    category: "healthcare",
    openingHours: "Mon-Fri 8.30am-8.30pm, Sat 8.30am-4pm",
    multilingualBlurb: blurb("Information on home care, community care, day care, and senior support services."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "scdf_emergency",
    name: "SCDF Emergency Ambulance",
    hotline: "995",
    category: "healthcare",
    openingHours: "24 hours",
    multilingualBlurb: blurb("Medical emergencies and ambulance dispatch. Call only for genuine emergencies."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "police_non_emergency",
    name: "Singapore Police Non-Emergency",
    hotline: "1800-255-0000",
    category: "legal",
    openingHours: "24 hours",
    multilingualBlurb: blurb("Non-urgent police matters. For emergencies dial 999."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "legal_aid_bureau",
    name: "Legal Aid Bureau",
    hotline: "1800-325-1424",
    category: "legal",
    openingHours: "Mon-Fri 8.30am-5pm",
    multilingualBlurb: blurb("Civil legal aid for those who qualify on means and merits."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "family_service_centre",
    name: "Family Service Centre (nearest branch)",
    category: "social_services",
    multilingualBlurb: blurb("Counselling, family support, and social services. Refer to the nearest FSC."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "silver_generation_office",
    name: "Silver Generation Office",
    hotline: "1800-650-6060",
    category: "social_services",
    multilingualBlurb: blurb("Outreach and information for seniors on schemes and benefits."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "comcare_hotline",
    name: "ComCare Hotline",
    hotline: "1800-222-0000",
    category: "financial_assistance",
    openingHours: "Mon-Fri 8.30am-6pm, Sat 8.30am-1pm",
    multilingualBlurb: blurb("Financial assistance for low-income individuals and families."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "cpf_senior_hotline",
    name: "CPF Senior Helpline",
    hotline: "1800-227-1188",
    category: "financial_assistance",
    openingHours: "Mon-Fri 8am-5.30pm",
    multilingualBlurb: blurb("CPF withdrawals, retirement payouts, and MediSave matters."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "peoples_association",
    name: "People's Association (Community Centre)",
    hotline: "6225-5322",
    category: "elderly_activity",
    multilingualBlurb: blurb("Senior activities, courses, and Community Centre programmes."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "active_ageing_centre",
    name: "Active Ageing Centre (nearest branch)",
    category: "elderly_activity",
    multilingualBlurb: blurb("Drop-in centres for seniors offering activities, befriending, and light support."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "skillsfuture_singapore",
    name: "SkillsFuture Singapore",
    hotline: "6785-5785",
    category: "digital_help",
    openingHours: "Mon-Fri 9am-6pm",
    multilingualBlurb: blurb("Digital and skills training, including senior-friendly courses."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "sg_digital_office_seniors_go_digital",
    name: "Seniors Go Digital",
    category: "digital_help",
    multilingualBlurb: blurb("One-on-one help with mobile apps, Singpass, and government e-services."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "mp_meet_the_people_session",
    name: "MP Meet-the-People Session",
    category: "mp_meet_the_people",
    openingHours: "Weekly, varies by constituency",
    multilingualBlurb: blurb("Weekly session where residents can request help from their elected MP."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "rc_visit",
    name: "Residents' Committee Visit",
    category: "rc_visit",
    multilingualBlurb: blurb("Local Residents' Committee volunteers can follow up on neighbourhood and welfare matters."),
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "queenstown_smc_mps",
    name: "Queenstown SMC Meet-the-People Session",
    hotline: "9811 3883",
    address: "Blk 3 Jalan Bukit Merah, #01-5118, Singapore 150003",
    category: "mp_meet_the_people",
    openingHours: "Mondays, 7:00 PM - 10:00 PM; closed on public holidays",
    url: "https://www.tptc.org.sg/our-mps/",
    multilingualBlurb: blurb("Eric Chua's Queenstown SMC session for appeals, letters, municipal issues, and agency follow-up."),
    latitude: 1.287133554639335,
    longitude: 103.8070005167375,
    walkingDirectionsHint: "The session is at the same Blk 3 void-deck cluster as the kiosk; look for #01-5118.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "thong_kheng_aac_queenstown",
    name: "Thong Kheng Active Ageing Centre and SGH Community Health Post",
    hotline: "6278 3966",
    address: "Blk 3 Jalan Bukit Merah, #01-5070, Singapore 150003",
    category: "elderly_activity",
    openingHours: "AAC: Mon-Fri 9:00 AM - 5:00 PM, Sat 9:00 AM - 1:00 PM; SGH CHP: Mon-Tue 9:00 AM - 4:00 PM",
    url: "https://www.sgh.com.sg/community-care/find-a-community-nursing-post",
    multilingualBlurb: blurb("Active ageing, check-ins, activities, and selected-day SGH community health support at Blk 3."),
    latitude: 1.2869998,
    longitude: 103.8068642,
    walkingDirectionsHint: "Stay within the Blk 3 void-deck cluster and look for unit #01-5070.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "hock_san_zone_rc",
    name: "Hock San Zone Residents' Committee and Dementia Go-To Point",
    hotline: "6474 1681",
    address: "Blk 3 Jalan Bukit Merah, #01-5054, Singapore 150003",
    category: "rc_visit",
    openingHours: "Mondays, 6:00 PM - 10:00 PM for Dementia Go-To Point listing; call before visiting",
    multilingualBlurb: blurb("Local RC touchpoint and Dementia Go-To Point for neighbourhood help and caregiver guidance."),
    latitude: 1.287166,
    longitude: 103.806875,
    walkingDirectionsHint: "Stay within the Blk 3 void-deck cluster and look for unit #01-5054.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "servicesg_bukit_merah",
    name: "ServiceSG Centre Bukit Merah",
    hotline: "6031 3890",
    address: "166 Bukit Merah Central, #03-3529A, Singapore 150166",
    category: "digital_help",
    openingHours: "Daily, 9:00 AM - 6:00 PM; closed Sundays and public holidays",
    url: "https://www.life.gov.sg/services-tools/book-virtual-appointment-servicesg",
    multilingualBlurb: blurb("One-stop government service centre with assisted access to services across public agencies."),
    latitude: 1.283092625749734,
    longitude: 103.8176672025981,
    walkingDirectionsHint: "Follow the mapped path east toward Bukit Merah Central and use the lift to #03-3529A.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "bukit_merah_polyclinic",
    name: "SingHealth Polyclinics - Bukit Merah",
    hotline: "6643 6969",
    address: "Blk 163 Bukit Merah Central, #04-3565, Singapore 150163",
    category: "healthcare",
    openingHours: "Mon-Fri 8:00 AM - 1:00 PM and 2:00 PM - 4:30 PM; Sat 8:00 AM - 12:30 PM",
    url: "https://polyclinic.singhealth.com.sg/our-polyclinics/shp-bukit-merah",
    multilingualBlurb: blurb("Public primary care clinic for acute care, chronic follow-up, vaccination, and screening."),
    latitude: 1.28370343137554,
    longitude: 103.8170515228158,
    walkingDirectionsHint: "Head toward Bukit Merah Central, then use the lifts at Blk 162/163 to reach the clinic level.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "bukit_merah_community_centre",
    name: "Bukit Merah Community Centre",
    hotline: "6474 1097",
    address: "4000 Jalan Bukit Merah, Singapore 159465",
    category: "elderly_activity",
    openingHours: "Daily, 9:00 AM - 10:00 PM; payment hours may differ",
    url: "https://www.pa.gov.sg/our-network/community-clubs/",
    multilingualBlurb: blurb("Community centre with PA counter, courses, facilities, and neighbourhood activities."),
    latitude: 1.285420091857,
    longitude: 103.8158981689434,
    walkingDirectionsHint: "Follow the mapped path east along Jalan Bukit Merah and check counter hours before visiting.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
  {
    key: "tanjong_pagar_town_council",
    name: "Tanjong Pagar Town Council",
    hotline: "1800-272-6415",
    address: "166 Bukit Merah Central, #03-3527, Singapore 150166",
    category: "town_council",
    openingHours: "Mon-Fri, 8:00 AM - 5:00 PM; closed weekends and public holidays",
    url: "https://www.tptc.org.sg/",
    multilingualBlurb: blurb("Town council contact for common-area estate maintenance such as lights, cleanliness, and hazards."),
    latitude: 1.283092625749734,
    longitude: 103.8176672025981,
    walkingDirectionsHint: "Follow the mapped path east toward Bukit Merah Central and use the lift to #03-3527.",
    active: true,
    source: "seed",
    updatedAt: UPDATED_AT,
  },
];
